# Runs ONLY on frontendLSEC2.
# Replace MONITORING_PRIVATE_IP with monitoringLS's PRIVATE IP (same VPC).
server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /metrics {
        proxy_pass http://MONITORING_PRIVATE_IP:8000;
    }

    location /trigger {
        proxy_pass http://MONITORING_PRIVATE_IP:8000;
    }
}
